substitutions:
  board_name: 'invertor-battery'
  static_ip: '192.168.0.163'
  scan_duration: !secret scan_duration
  update_interval: !secret update_interval

esphome:
  name: ${board_name}
  platform: ESP8266
  board: nodemcuv2

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml

sensor:
  - platform: adc
    filters:
      - multiply: 15
      - sliding_window_moving_average:
          window_size: 90
          send_every: 30
    pin: A0
    name: "Battery Pack VCC"
    id: battery_pack_vcc
    update_interval: 1s
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2
    icon: mdi:car-battery

  - platform: adc
    filters:
      - multiply: 15
    pin: A0
    internal: True
    name: "Battery Pack VCC Internal"
    id: battery_pack_vcc_internal
    update_interval: 1s
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2
    icon: mdi:car-battery

  - platform: template
    name: "Battery Pack Level"
    id: battery_pack_level
    update_interval: 60s
    device_class: "battery"
    state_class: "measurement"
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: mdi:car-battery
    lambda: |-
      if ((id(battery_pack_vcc).state >= 12.75)) { return 100; }
      else if ((id(battery_pack_vcc).state >= 12.75)) { return 100; }
      else { return (id(battery_pack_vcc).state - 10.75) * 50; }

display:
  platform: tm1637
  clk_pin: D6
  dio_pin: D5
  update_interval: 250ms
  lambda: |-
    it.printf("%.2f", id(battery_pack_vcc).state );

binary_sensor:
  - platform: homeassistant
    name: "main_power_fail"
    id: main_power_fail
    entity_id: binary_sensor.main_power_fail