substitutions:
  board_name: 'invertor-battery'
  static_ip: '192.168.0.163'
  number: '22'

esphome:
  name: ${board_name}
  platform: ESP8266
  board: d1_mini

packages:
  device_base: !include packages/1wifi_api_ota_logger_mqtt.yaml
  base_sensors: !include packages/2common_sensors.yaml
  led: !include packages/3status_led_esp8266.yaml

sensor:
  - platform: adc
    pin: A0
    name: "Invertor VCC"
    update_interval: 3s